version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filestorage_app
    ports:
      - "8080:80"
    privileged: true  # Required for VPN and network management
    environment:
      VPN_SERVER: vdi.fhict.nl
      VPN_USER: i472595
      VPN_PASSWORD: Eqp40XwOw5
      SQL_CONNECTION_STRING: "Server=mssqlstud.fhict.local;Database=dbi472595;User Id=dbi472595;Password=database;MultipleActiveResultSets=true;TrustServerCertificate=True"
      MONGODB_CONNECTION_STRING: "mongodb+srv://472595:mongodatabase@clusterfilestorage.en7np.mongodb.net/?retryWrites=true&w=majority&appName=ClusterFileStorage&authMechanism=SCRAM-SHA-1"
    volumes:
      - ./vpn-connect.sh:/app/vpn-connect.sh  # Mount the VPN script
    command: ["/app/vpn-connect.sh"]  # Execute the script as the entrypoint
    restart: always  # Automatically restart the container on failure
