version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: filestorageapp
    ports:
      - "8080:80"
    privileged: true  # Required for VPN and network management
    environment:
      SQL_CONNECTION_STRING: "Server=mssqlstud.fhict.local;Database=dbi472595;User Id=dbi472595;Password=database;MultipleActiveResultSets=true;TrustServerCertificate=True"
      MONGODB_CONNECTION_STRING: "mongodb+srv://472595:mongodatabase@clusterfilestorage.en7np.mongodb.net/?retryWrites=true&w=majority&appName=ClusterFileStorage&authMechanism=SCRAM-SHA-1"
    volumes:
      - ./dataProtectionKeys:/root/.aspnet/DataProtection-Keys  # This mounts a volume for data protection keys
    restart: always  # Automatically restart the container on failure
