name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 
          -e GITHUB_ACTIONS=true 
          -e CI=true
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore FileStorage.sln

      # Step 4: Build the Solution
      - name: Build the solution
        run: dotnet build FileStorage.sln --configuration Release

      # Step 5: Install ReportGenerator tool globally
      - name: Install ReportGenerator tool
        run: |
          dotnet tool install --global dotnet-reportgenerator-globaltool
          export PATH="$PATH:/root/.dotnet/tools"  # Ensure it's available in PATH

      # Step 6: Run Unit Tests with Code Coverage
      - name: Run Unit Tests with Code Coverage
        continue-on-error: true
        run: |
          dotnet test FileStorage.sln --configuration Release --collect:"XPlat Code Coverage" \
            --logger "trx;LogFileName=test_results.trx"
          reportgenerator \
            -reports:**/coverage.cobertura.xml \
            -targetdir:./coverage-report \
            -reporttypes:Html
        env:
          DOTNET_ROOT: /usr/share/dotnet

      # Step 7: Install SonarQube Cloud scanner if Not Cached
      - name: Install SonarQube Cloud scanner if not cached
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --tool-path ./.sonar/scanner
          
      # Step 8: SonarQube Analysis (with coverage report directly sent to SonarCloud)
      - name: Run SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"CamielAdriaens_FileStorageServer2" \
            /o:"camieladriaens" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"
          # Build the project after the sonar scanner begins
          dotnet build FileStorage.sln --configuration Release
          # Complete the SonarQube analysis
          ./.sonar/scanner/dotnet-sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"

      # Step 9: Check Docker Version
      - name: Check Docker Version
        run: docker --version

      # Step 10: List Docker Images
      - name: List Docker Images
        run: docker images

      # Step 11: List Running Docker Containers
      - name: List Running Docker Containers
        run: docker ps

      # Step 12: Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 13: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 14: Build Docker Image
      - name: Build Docker Image
        run: |
          docker build -t camieladriaen/filestorageserverapp:${{ github.sha }} .

      # Step 15: Tag Docker Image as Latest
      - name: Tag Docker Image as Latest
        run: |
          docker tag camieladriaen/filestorageserverapp:${{ github.sha }} camieladriaen/filestorageserverapp:latest

      # Step 16: Push Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push camieladriaen/filestorageserverapp:${{ github.sha }}
          docker push camieladriaen/filestorageserverapp:latest
