name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 
          -e GITHUB_ACTIONS=true 
          -e CI=true

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore FileStorage.sln

      # Step 4: Build the Solution
      - name: Build the solution
        run: dotnet build FileStorage.sln --configuration Release

      # Step 5: Run Unit Tests with Code Coverage
      - name: Run Unit Tests with Code Coverage
        run: |
          mkdir -p TestResults/coverage  # Ensure the coverage folder exists
          dotnet test FileStorage.Tests/FileStorage.Tests.csproj \
            --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/coverage/ \
            /p:CoverletOutputFormat=opencover \
            --verbosity normal
          
          # List the contents of TestResults/coverage/ to verify if the file was created
          echo "Listing contents of TestResults/coverage/"
          ls -l TestResults/coverage/

      # Step 6: Debug Test Results and Coverage Files
      - name: List TestResults Directory
        run: |
          echo "Listing contents of TestResults/ directory"
          ls -R TestResults/

      - name: List Coverage Directory
        run: |
          echo "Listing contents of TestResults/coverage/ directory"
          ls -R TestResults/coverage/

      # Step 7: Upload Test Results
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: TestResults/
          if-no-files-found: warn
          include-hidden-files: false

      # Step 8: Upload Coverage Report
      - name: Upload Coverage Report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: TestResults/coverage/coverage.opencover.xml
          if-no-files-found: warn
          include-hidden-files: false

      # Step 9: Cache SonarQube Cloud Scanner
      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ./.sonar/scanner
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      # Step 10: Install SonarQube Cloud Scanner if Not Cached
      - name: Install SonarQube Cloud scanner if not cached
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --tool-path ./.sonar/scanner

      # Step 11: Build and Analyze with SonarQube
      - name: Build and analyze with SonarQube
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"CamielAdriaens_FileStorageServer2" \
            /o:"camieladriaens" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.cs.opencover.reportsPaths="TestResults/coverage/coverage.opencover.xml"
          dotnet build FileStorage.sln --configuration Release
          ./.sonar/scanner/dotnet-sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
