name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Display Directory Structure
        run: |
          echo "Displaying directory structure for debugging:"
          ls -R
          ls -R MODELS

      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'  # Update to the correct .NET version

      - name: Restore dependencies
        run: dotnet restore FileStorage.sln

      - name: Build the solution
        run: dotnet build FileStorage.sln --configuration Release

      - name: Run Unit Tests
        run: dotnet test FileStorage.sln --no-build --verbosity normal
