name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 
          -e GITHUB_ACTIONS=true 
          -e CI=true

    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore FileStorage.sln

      # Step 4: Build the Solution
      - name: Build the solution
        run: dotnet build FileStorage.sln --configuration Release

      # Step 5: Install Coverlet and run tests with coverage
      - name: Run Unit Tests with Code Coverage
        run: |
          # Install Coverlet for coverage collection
          dotnet tool install --global coverlet.console

          # Run tests with coverage and send results to SonarCloud
          dotnet test FileStorage.Tests/FileStorage.Tests.csproj \
            --no-build --configuration Release \
            --collect:"XPlat Code Coverage" \
            /p:SonarQube=true \
            /p:sonar.coverageReportPaths="TestResults/*/coverage.cobertura.xml"

      # Step 6: Install SonarQube Cloud Scanner
      - name: Install SonarQube Cloud scanner if not cached
        run: |
          mkdir -p ./.sonar/scanner
          dotnet tool install dotnet-sonarscanner --tool-path ./.sonar/scanner

      # Step 7: SonarQube Analysis (direct to SonarCloud)
      - name: Run SonarQube analysis
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          ./.sonar/scanner/dotnet-sonarscanner begin \
            /k:"CamielAdriaens_FileStorageServer2" \
            /o:"camieladriaens" \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.verbose=true
          
          # Build the project after the sonar scanner begins
          dotnet build FileStorage.sln --configuration Release

          # Complete the SonarQube analysis
          ./.sonar/scanner/dotnet-sonarscanner end \
            /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
