name: CI/CD Pipeline

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo:5.0
        ports:
          - 27017:27017
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand(\"ping\")'" 
          --health-interval=10s 
          --health-timeout=5s 
          --health-retries=5 
          -e GITHUB_ACTIONS=true 
          -e CI=true
    steps:
      # Step 1: Checkout Code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'

      # Step 3: Restore Dependencies
      - name: Restore dependencies
        run: dotnet restore FileStorage.sln

      # Step 4: Build the Solution
      - name: Build the solution
        run: dotnet build FileStorage.sln --configuration Release

      # Step 5: Run Unit Tests with Code Coverage
      - name: Run Unit Tests with Code Coverage
        run: |
          mkdir -p TestResults/coverage
          dotnet test FileStorage.Tests/FileStorage.Tests.csproj \
            --no-build --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutput=TestResults/coverage/ \
            /p:CoverletOutputFormat=cobertura \
            --verbosity normal
        continue-on-error: true

      # Step 6: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 7: Build and Push Backend Docker Image
      - name: Build and Push Backend Docker Image
        run: |
          docker build -t camieladriaen/filestorageserverapp:${{ github.sha }} -t camieladriaen/filestorageserverapp:latest ./FileStorageServer2
          docker push camieladriaen/filestorageserverapp:${{ github.sha }}
          docker push camieladriaen/filestorageserverapp:latest

